/* Generated By:JJTree: Do not edit this line. ASTComparison.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.hillayes.query.filter.parser;

public
class ASTComparison extends SimpleNode {
  public ASTComparison(int id) {
    super(id);
  }

  public ASTComparison(FilterParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FilterParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b484b504b519554cab3a774328b2d235 (do not edit this line) */
