/* Generated By:JJTree: Do not edit this line. ASTparse.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.hillayes.query.filter.parser;

public
class ASTparse extends SimpleNode {
  public ASTparse(int id) {
    super(id);
  }

  public ASTparse(FilterParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FilterParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=17bb9b5a9449ae6a01213c1b0ddae077 (do not edit this line) */
