/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 5.0 */
package com.hillayes.query.filter.parser;

public interface FilterParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTVOID = 1;
  public int JJTOR = 2;
  public int JJTAND = 3;
  public int JJTNOT = 4;
  public int JJTCOMPARISON = 5;


  public String[] jjtNodeName = {
    "parse",
    "void",
    "Or",
    "And",
    "Not",
    "Comparison",
  };
}
/* JavaCC - OriginalChecksum=43951c1c415db64b8e6a5f037a16f58b (do not edit this line) */
