/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 7.0.12 */
package com.hillayes.query.filter.parser;

public interface FilterParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTVOID = 1;
  public int JJTOR = 2;
  public int JJTAND = 3;
  public int JJTNOT = 4;
  public int JJTCOMPARISON = 5;


  public String[] jjtNodeName = {
    "parse",
    "void",
    "Or",
    "And",
    "Not",
    "Comparison",
  };
}
/* JavaCC - OriginalChecksum=31e9d19daa64484c32501c2ee2975a33 (do not edit this line) */
