/* Generated By:JavaCC: Do not edit this line. FilterParserDefaultVisitor.java Version 7.0.12 */
package com.hillayes.query.filter.parser;

public class FilterParserDefaultVisitor implements FilterParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTparse node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAnd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTComparison node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=f960751f53b527ed5f71d21594fbe83c (do not edit this line) */
