/* Generated By:JavaCC: Do not edit this line. FilterParserVisitor.java Version 7.0.12 */
package com.hillayes.query.filter.parser;

public interface FilterParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTparse node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTComparison node, Object data);
}
/* JavaCC - OriginalChecksum=cfed7ff918468acac9209246b11ed408 (do not edit this line) */
