/* Generated By:JavaCC: Do not edit this line. FilterParserVisitor.java Version 5.0 */
package com.hillayes.query.filter.parser;

public interface FilterParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTparse node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTComparison node, Object data);
}
/* JavaCC - OriginalChecksum=ff8544950e8b1ddafdb393543e22ebc7 (do not edit this line) */
