name: Build and Deploy CI with Maven

on:
  release:
    types: [ published ]

jobs:
  build:
    name: package and deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'maven'

    - name: Build with Maven
      # skips the tests due to lack of "test" profile
      run: |
        mvn -B deploy -Drevision=${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
